logging.level:
  org.springframework: info
  customers: debug
  
server:
  port: 5000

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://yurmont-dbserver.mysql.database.azure.com:3306/customers?useSSL=true&requireSSL=false&autoReconnect=true&serverTimezone=UTC
    username: yurmont-dbuser@yurmont-dbserver
    password: Xzz|Vcc100
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    validationQuery: select 1
    testOnBorrow: true
    maxActive: 20
    maxIdle: 10
    maxWait: -1
    
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 0   

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug