logging.level:
  org.springframework: info
  customers: debug
  
server:
  port: 8080

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/customers?useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    validationQuery: select 1
    testOnBorrow: true
    maxActive: 20
    maxIdle: 10
    maxWait: -1
    
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 0   

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug